/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HeroPlaceholder {
        /**
          * @default "Hero AntD"
         */
        "name": string;
    }
}
declare global {
    interface HTMLHeroPlaceholderElement extends Components.HeroPlaceholder, HTMLStencilElement {
    }
    var HTMLHeroPlaceholderElement: {
        prototype: HTMLHeroPlaceholderElement;
        new (): HTMLHeroPlaceholderElement;
    };
    interface HTMLElementTagNameMap {
        "hero-placeholder": HTMLHeroPlaceholderElement;
    }
}
declare namespace LocalJSX {
    interface HeroPlaceholder {
        /**
          * @default "Hero AntD"
         */
        "name"?: string;
    }
    interface IntrinsicElements {
        "hero-placeholder": HeroPlaceholder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hero-placeholder": LocalJSX.HeroPlaceholder & JSXBase.HTMLAttributes<HTMLHeroPlaceholderElement>;
        }
    }
}
